

Medium.destroy_all
User.destroy_all
Tag.destroy_all
QueuedMedium.destroy_all
Type.destroy_all

User.create(name: "Joey", password: "password", admin: true, email: "joey@joey.com")
User.create(name: "Shane", password: "password", admin: true, email: "shane@shane.com")
User.create(name: "Song", password: "password", admin: true, email: "song@song.com")

Type.create(name: "Book")
Type.create(name: "TV Show")
Type.create(name: "Movie")
Type.create(name: "Video Game")
Type.create(name: "Podcast")

Tag.create(name: "Horror")
Tag.create(name: "Animated")
Tag.create(name: "Animals")

movies = [
    {title: "Signs", type: Type.third},
    {title: "Prisoners", type: Type.third},
    {title: "The Grand Budapest Hotel", type: Type.third},
    {title: "Inception", type: Type.third},
    {title: "The Wolf of Wall Street", type: Type.third},
    {title: "Mad Max: Fury Road", type: Type.third},
    {title: "Toy Story 3", type: Type.third},
    {title: "Whiplash", type: Type.third},
    {title: "Spotlight", type: Type.third},
    {title: "Manchester by the Sea", type: Type.third},
    {title: "Birdman", type: Type.third},
    {title: "Boyhood", type: Type.third},
    {title: "Inside Out", type: Type.third},
    {title: "Dunkirk", type: Type.third},
    {title: "Black Swan", type: Type.third},
    {title: "Gone Girl", type: Type.third},
    {title: "Blade Runner 2049", type: Type.third},
    {title: "The Imitation Game", type: Type.third},
    {title: "Your Name", type: Type.third},
    {title: "12 Years a Slave", type: Type.third},
    {title: "The King's Speech", type: Type.third},
    {title: "Django Unchained", type: Type.third},
    {title: "Interstellar", type: Type.third},
    {title: "The Tree of Life", type: Type.third},
    {title: "La La Land", type: Type.third},
    {title: "Logan", type: Type.third},
    {title: "The Social Network", type: Type.third},
    {title: "Arrival", type: Type.third},
    {title: "Before Midnight", type: Type.third},
    {title: "Nebraska", type: Type.third},
    {title: "Phantom Thread", type: Type.third},
    {title: "Argo", type: Type.third},
    {title: "Hacksaw Ridge", type: Type.third},
    {title: "The Revenant", type: Type.third},
    {title: "Moonrise Kingdom", type: Type.third},
    {title: "Captain Fantastic", type: Type.third},
    {title: "Nightcrawler", type: Type.third},
    {title: "Her", type: Type.third},
    {title: "Hidden Figures", type: Type.third},
    {title: "Edge of Tomorrow", type: Type.third},
    {title: "The Perks of Being a Wallflower", type: Type.third},
    {title: "Bridge of Spies", type: Type.third},
    {title: "Call Me By Your Name", type: Type.third},
    {title: "The Master", type: Type.third},
    {title: "The Big Short", type: Type.third},
    {title: "The Avengers", type: Type.third},
    {title: "The Disaster Artist", type: Type.third},
    {title: "The Dark Knight Rises", type: Type.third},
    {title: "The Martian", type: Type.third},
    {title: "Zero Dark Thirty", type: Type.third},
    {title: "Life of Pi", type: Type.third},
    {title: "Dawn of the Planet of the Apes", type: Type.third},
    {title: "The Theory of Everything", type: Type.third},
    {title: "Captain Phillips", type: Type.third},
    {title: "Moonlight", type: Type.third},
    {title: "Lady Bird", type: Type.third},
    {title: "Midnight in Paris", type: Type.third},
    {title: "Gravity", type: Type.third},
    {title: "Guardians of the Galaxy", type: Type.third},
    {title: "Ex Machina", type: Type.third},
    {title: "Hell or High Water", type: Type.third},
    {title: "Silver Linings Playbook", type: Type.third},
    {title: "Baby Driver", type: Type.third},
    {title: "Drive", type: Type.third},
    {title: "Lion", type: Type.third},
    {title: "Coco", type: Type.third},
    {title: "Steve Jobs", type: Type.third},
    {title: "Skyfall", type: Type.third},
    {title: "Sicario", type: Type.third},
    {title: "A Monster Calls", type: Type.third},
    {title: "Harry Potter and the Deathly Hallows: Part 1", type: Type.third},
    {title: "Harry Potter and the Deathly Hallows: Part 2", type: Type.third},
    {title: "The Girl with the Dragon Tattoo", type: Type.third},
    {title: "Moneyball", type: Type.third},
    {title: "Silence", type: Type.third},
    {title: "Carol", type: Type.third},
    {title: "The Shape of Water", type: Type.third},
    {title: "The Hateful Eight", type: Type.third},
    {title: "Room", type: Type.third},
    {title: "Paterson", type: Type.third},
    {title: "X-Men: Days of Future Past", type: Type.third},
    {title: "Dallas Buyers Club", type: Type.third},
    {title: "The Florida Project", type: Type.third},
    {title: "The Artist", type: Type.third},
    {title: "Les Miserables", type: Type.third},
    {title: "How to Train Your Dragon", type: Type.third},
    {title: "The Help", type: Type.third},
    {title: "Get Out", type: Type.third},
    {title: "Captain America: Civil War", type: Type.third},
    {title: "The Raid", type: Type.third},
    {title: "The Raid 2", type: Type.third},
    {title: "Wind River", type: Type.third},
    {title: "Fury", type: Type.third},
    {title: "Lincoln", type: Type.third},
    {title: "The World's End", type: Type.third},
    {title: "Mission Impossible: Ghost Protocol", type: Type.third},
    {title: "Tinker Taylor Soldier Spy", type: Type.third},
    {title: "Three Billboards Outside Ebbing, Missouri", type: Type.third},
    {title: "Looper", type: Type.third},
    {title: "Star Wars: Episode I - The Phantom Menace", type: Type.third},
    {title: "Star Wars: Episode II - Attack of the Clones", type: Type.third},
    {title: "Star Wars: Episode III - Revenge of the Sith", type: Type.third},
    {title: "Star Wars: Episode IV - A New Hope", type: Type.third},
    {title: "Star Wars: Episode V - The Empire Strikes Back", type: Type.third},
    {title: "Star Wars: Episode VI - Return of the Jedi", type: Type.third},
    {title: "Star Wars: Episode VII - The Force Awakens", type: Type.third},
    {title: "Star Wars: Episode VII - The Last Jedi", type: Type.third},
    {title: "Hunt for the Wilderpeople", type: Type.third},
    {title: "The Conjuring", type: Type.third},
    {title: "American Hustle", type: Type.third},
    {title: "Pulp Fiction", type: Type.third},
    {title: "Schindler's List", type: Type.third},
    {title: "Malcolm X", type: Type.third},
    {title: "Princess Mononoke", type: Type.third},
    {title: "Magnolia", type: Type.third},
    {title: "Europa", type: Type.third},
    {title: "Sense and Sensibility", type: Type.third},
    {title: "Life is Beautiful", type: Type.third},
    {title: "Goodfellas", type: Type.third},
    {title: "Rushmore", type: Type.third},
    {title: "The Silence of the Lambs", type: Type.third},
    {title: "Hamlet", type: Type.third},
    {title: "Dreams", type: Type.third},
    {title: "Hard Boiled", type: Type.third},
    {title: "Fargo", type: Type.third},
    {title: "Eat Drink Man Woman", type: Type.third},
    {title: "The Shawshank Redemption", type: Type.third},
    {title: "Audition", type: Type.third},
    {title: "Dead Man Walking", type: Type.third},
    {title: "The Sweet Hereafter", type: Type.third},
    {title: "The Player", type: Type.third},
    {title: "Once Upon a Time in China", type: Type.third},
    {title: "The Wedding Banquet", type: Type.third},
    {title: "Breaking the Waves", type: Type.third},
    {title: "Toy Story", type: Type.third},
    {title: "Chasing Amy", type: Type.third},
    {title: "Rosencrantz & Guildenstern Are Dead", type: Type.third},
    {title: "Perfect Blue", type: Type.third},
    {title: "The Nightmare Before Christmas", type: Type.third},
    {title: "Being John Malkovich", type: Type.third},
    {title: "Quiz Show", type: Type.third},
    {title: "Saving Private Ryan", type: Type.third},
    {title: "Barton Fink", type: Type.third},
    {title: "Porco Rosso", type: Type.third},
    {title: "Dead Man", type: Type.third},
    {title: "Fear and Loathing in Las Vegas", type: Type.third},
    {title: "Philadelphia", type: Type.third},
    {title: "Raise the Red Lantern", type: Type.third},
    {title: "The Ice Storm", type: Type.third},
    {title: "Felicia's Journey", type: Type.third},
    {title: "Only Yesterday", type: Type.third},
    {title: "Reversal of Fortune", type: Type.third},
    {title: "Secrets and Lies", type: Type.third},
    {title: "Unforgiven", type: Type.third},
    {title: "Romance", type: Type.third},
    {title: "Whisper of the Heart", type: Type.third},
    {title: "Amistad", type: Type.third},
    {title: "Natural Born Killers", type: Type.third},
    {title: "Bound", type: Type.third},
    {title: "The Remains of the Day", type: Type.third},
    {title: "The Usual Suspects", type: Type.third},
    {title: "The Adjuster", type: Type.third},
    {title: "Pleasentville", type: Type.third},
    {title: "Bad Lieutenant", type: Type.third},
    {title: "The Cider House Rules", type: Type.third},
    {title: "Until the End of the World", type: Type.third},
    {title: "Boogie Nights", type: Type.third},
    {title: "Memories", type: Type.third},
    {title: "Rhapsody in August", type: Type.third},
    {title: "The People vs. Larry Flint", type: Type.third},
    {title: "Dark City", type: Type.third},
    {title: "Naked Lunch", type: Type.third},
    {title: "Calendar", type: Type.third},
    {title: "My Neighbours the Yamadas", type: Type.third},
    {title: "Face/Off", type: Type.third},
    {title: "Reservoir Dogs ", type: Type.third},
    {title: "L.A. Confidential", type: Type.third},
    {title: "A Perfect World", type: Type.third},
    {title: "Michael Collins", type: Type.third},
    {title: "Fight Club", type: Type.third},
    {title: "Ed Wood", type: Type.third},
    {title: "Bottle Rocket", type: Type.third},
    {title: "Se7en", type: Type.third},
    {title: "Edward Scissorhands", type: Type.third},
    {title: "Jackie Brown", type: Type.third},
    {title: "American History X", type: Type.third},
    {title: "Apollo 13", type: Type.third},
    {title: "The Fugitive", type: Type.third},
    {title: "Clerks", type: Type.third},
    {title: "Dances with Wolves", type: Type.third},
    {title: "Stealing Beauty", type: Type.third},
    {title: "The Madness of King George", type: Type.third},
    {title: "The Joy Luck Club", type: Type.third},
    {title: "Central Station", type: Type.third},
    {title: "Babe", type: Type.third},
    {title: "Sling Blade", type: Type.third},
    {title: "Pom Poko", type: Type.third},
    {title: "Terminator 2: Judgement Day", type: Type.third},
    {title: "Midnight in the Garden of Good and Evil", type: Type.third},
    {title: "Shadow Lands", type: Type.third},
    {title: "Gattaca", type: Type.third},
    {title: "The Matrix", type: Type.third},
    {title: "Bram Stoker's Dracula", type: Type.third},
    {title: "The Godfather: Part III", type: Type.third},
    {title: "Serenity", type: Type.third},
]

tv_shows = [

    {title: "Eastbound and Down", type: Type.second},
    {title: "Oz", type: Type.second},
    {title: "The Golden Girls", type: Type.second},
    {title: "Portlandia", type: Type.second},
    {title: "Gunsmoke", type: Type.second},
    {title: "Key & Peele", type: Type.second},
    {title: "Mystery Science Theater 3000", type: Type.second},
    {title: "Broad City", type: Type.second},
    {title: "Homeland", type: Type.second},
    {title: "Party Down", type: Type.second},
    {title: "Doctor Who", type: Type.second},
    {title: "Good Times", type: Type.second},
    {title: "The Real World", type: Type.second},
    {title: "House of Cards", type: Type.second},
    {title: "The Jeffersons", type: Type.second},
    {title: "Dallas", type: Type.second},
    {title: "Thirty Something", type: Type.second},
    {title: "The Walking Dead", type: Type.second},
    {title: "American Crime Story: The People vs. O.J. Simpson", type: Type.second},
    {title: "Transparent", type: Type.second},
    {title: "Girls", type: Type.second},
    {title: "Mr. Show", type: Type.second},
    {title: "Rosanne", type: Type.second},
    {title: "The State", type: Type.second},
    {title: "The Odd Couple", type: Type.second},
    {title: "Downton Abbey", type: Type.second},
    {title: "Happy Days", type: Type.second},
    {title: "Chapelle's Show", type: Type.second},
    {title: "The Wonder Years", type: Type.second},
    {title: "Sex and the City", type: Type.second},
    {title: "Your Show of Shows", type: Type.second},
    {title: "Beavis and Butt-Head", type: Type.second},
    {title: "Hill Street Blues", type: Type.second},
    {title: "Roots", type: Type.second},
    {title: "Fawlty Towers", type: Type.second},
    {title: "24", type: Type.second},
    {title: "Six Feet Under", type: Type.second},
    {title: "The Muppet Show", type: Type.second},
    {title: "Fargo", type: Type.second},
    {title: "ER", type: Type.second},
    {title: "Taxi", type: Type.second},
    {title: "The Office (U.S.)", type: Type.second},
    {title: "The Rockford Files", type: Type.second},
    {title: "Battlestar Galactica", type: Type.second},
    {title: "Columbo", type: Type.second},
    {title: "The Americans", type: Type.second},
    {title: "NYPD Blue", type: Type.second},
    {title: "The Shield", type: Type.second},
    {title: "Lost", type: Type.second},
    {title: "Buffy the Vampire Slayer", type: Type.second},
    {title: "Orange is the New Black", type: Type.second},
    {title: "Law & Order", type: Type.second},
    {title: "My So-Called Life", type: Type.second},
    {title: "30 Rock", type: Type.second},
    {title: "South Park", type: Type.second},
    {title: "Monty Python's Flying Circus", type: Type.second},
    {title: "The X-Files", type: Type.second},
    {title: "Arrested Development", type: Type.second},
    {title: "Friends", type: Type.second},
    {title: "Veep", type: Type.second},
    {title: "Friday Night Lights", type: Type.second},
    {title: "Deadwood", type: Type.second},
    {title: "Louie", type: Type.second},
    {title: "The Office (U.K.)", type: Type.second},
    {title: "Cheers", type: Type.second},
    {title: "Curb Your Enthusiasm", type: Type.second},
    {title: "Star Trek", type: Type.second},
    {title: "Star Trek: The Next Generation", type: Type.second},
    {title: "Star Trek: Deep Space Nine", type: Type.second},
    {title: "Star Trek: Voyager", type: Type.second},
    {title: "Star Trek: Enterprise", type: Type.second},
    {title: "Star Trek : Discovery", type: Type.second},
    {title: "Twin Peaks", type: Type.second},
    {title: "M*A*S*H", type: Type.second},
    {title: "The West Wing", type: Type.second},
    {title: "The Larry Sanders Show", type: Type.second},
    {title: "Game of Thrones", type: Type.second},
    {title: "Freaks and Geeks", type: Type.second},
    {title: "The Twilight Zone", type: Type.second},
    {title: "The Simpsons", type: Type.second},
    {title: "Seinfeld", type: Type.second},
    {title: "Mad Men", type: Type.second},
    {title: "Breaking Bad", type: Type.second},
    {title: "The Wire", type: Type.second},
    {title: "The Sopranos", type: Type.second},
    {title: "It's Always Sunny in Philadelphia", type: Type.second},
    {title: "Nathan For You", type: Type.second},
    {title: "Supernatural", type: Type .second},
    {title: "Angel", type: Type.second},
    {title: "Agents of S.H.I.E.L.D.", type: Type.second},
    {title: "Family Guy", type: Type.second},
    {title: "The Orville", type: Type.second},
    {title: "Babylon 5", type: Type.second},
    {title: "Stargate SG1", type: Type.second},
    {title: "Red Dwarf", type: Type.second},
    {title: "The I.T. Crowd", type: Type.second},
    {title: "Black Books", type: Type.second},
    {title: "Father Ted", type: Type.second},
    {title: "How I Met Your Mother", type: Type.second},
    {title: "Firefly", type: Type.second}

]

podcasts = [
    {title: "Shagged Married Annoyed", type: Type.fifth},
    {title: "David Tennant Does a Podcast With... ", type: Type.fifth},
    {title: "David Walliams' Marvellous Musical Podcast", type: Type.fifth},
    {title: "The Ron Burgundy Podcast", type: Type.fifth},
    {title: "The Intelligence", type: Type.fifth},
    {title: "The Joe Rogan Experience", type: Type.fifth},
    {title: "The Dropout", type: Type.fifth},
    {title: "Happy Place", type: Type.fifth},
    {title: "Desert Island Discs", type: Type.fifth},
    {title: "Off the Menu with Ed Gamble and James Acaster", type: Type.fifth},
    {title: "Quickly Kevin; will he score? The 90s Football Show", type: Type.fifth},
    {title: "Mindset with Muscle", type: Type.fifth},
    {title: "My Dad Wrote a Porno", type: Type.fifth},
    {title: "TED Talks Daily", type: Type.fifth},
    {title: "Fall of Shah", type: Type.fifth},
    {title: "Serial", type: Type.fifth},
    {title: "Duolingo Spanish Podcast", type: Type.fifth},
    {title: "Under The Skin with Russell Brand", type: Type.fifth},
    {title: "Friday Night Comedy from BBC Radio 4", type: Type.fifth},
    {title: "Paul McKenna's Positivity Podcast", type: Type.fifth},
    {title: "The Infinite Monkey Cage", type: Type.fifth},
    {title: "Making Sense with Sam Harris", type: Type.fifth},
    {title: "The Peter Crouch Podcast", type: Type.fifth},
    {title: "The Butterfly Effect with Jon Ronson", type: Type.fifth},
    {title: "No Such Thing as a Fish", type: Type.fifth},
    {title: "Today in Focus", type: Type.fifth},
    {title: "The Doctor's Kitchen Podcast", type: Type.fifth},
    {title: "THE ADAM BUXTON PODCAST", type: Type.fifth},
    {title: "Rugby Union Weekly", type: Type.fifth},
    {title: "The Rugby Pod", type: Type.fifth},
    {title: "Athletico Mince", type: Type.fifth},
    {title: "Happy Mum Happy Baby", type: Type.fifth},
    {title: "My Favourite Murder with Karen Kilgariff and Georgia Hardstark", type: Type.fifth},
    {title: "Feel Better, Live More with Dr Rangan Chatterjee", type: Type.fifth},
    {title: "Stuff You Should Know", type: Type.fifth},
    {title: "Origins with James Andrew Miller", type: Type.fifth},
    {title: "Woman's Hour", type: Type.fifth},
    {title: "The Guilty Feminist", type: Type.fifth},
    {title: "Casefile True Crime", type: Type.fifth},
    {title: "House of Rugby", type: Type.fifth},
    {title: "ITV 6 Nations Podcast", type: Type.fifth},
    {title: "The True Georgie Podcast", type: Type.fifth},
    {title: "Kermode and Mayo's Film Review", type: Type.fifth},
    {title: "Sleep With Me", type: Type.fifth},
    {title: "The Teacher's Pet", type: Type.fifth},
    {title: "Oprah's SuperSoul Conversations", type: Type.fifth},
    {title: "Standard Issue Podcast", type: Type.fifth},
    {title: "If I Can Do It", type: Type.fifth},
    {title: "More or Less: Behind the Scenes", type: Type.fifth},
    {title: "How I Built This with Guy Raz", type: Type.fifth},
    {title: "The Receipts Podcast", type: Type.fifth},
    {title: "How To Fail With Elizabeth Day", type: Type.fifth},
    {title: "In The Pink", type: Type.fifth},
    {title: "Fortunately... with Fi and Jane", type: Type.fifth},
    {title: "Eurovision Calling", type: Type.fifth},
    {title: "The Best of the Chris Evans Breakfast Show", type: Type.fifth},
    {title: "Dirty John", type: Type.fifth},
    {title: "Scummy Mummies - Podcast", type: Type.fifth},
    {title: "NHS Couch to 5k", type: Type.fifth},
    {title: "Bryony Gordon's Mad World", type: Type.fifth},
    {title: "Brexitcast", type: Type.fifth},
    {title: "Conviction", type: Type.fifth},
    {title: "The Hurricane Tapes", type: Type.fifth},
    {title: "99% Invisible", type: Type.fifth},
    {title: "The Richard Nicholls Podcast", type: Type.fifth},
    {title: "JaackMaate's Happy Hour with ImAlex", type: Type.fifth},
    {title: "Football Weekly", type: Type.fifth},
    {title: "How To Burn a Million Quid", type: Type.fifth},
    {title: "The Bodcast with Chloe Madeley", type: Type.fifth},
    {title: "The Tim Ferriss Show", type: Type.fifth},
    {title: "Dan Carlin's Hardcore History", type: Type.fifth},
    {title: "The Tony Robbins Podcast", type: Type.fifth},
    {title: "In Our Time", type: Type.fifth},
    {title: "OS GetOutside", type: Type.fifth},
    {title: "Practice You with elena Brower", type: Type.fifth},
    {title: "The Magic Sponge with Jimmy Bullard, Rob Beckett and Ian Smith", type: Type.fifth},
    {title: "The Economist Radio", type: Type.fifth},
    {title: "Global News Podcast", type: Type.fifth},
    {title: "FT News Briefing", type: Type.fifth},
    {title: "Freakonomics Radio", type: Type.fifth},
    {title: "Monster", type: Type.fifth},
    {title: "Will Greenwood's Rugby Podcast", type: Type.fifth},
    {title: "Like Minded Friends with Tom Allen & Suzi Ruffell", type: Type.fifth},
    {title: "The News Quiz Extra", type: Type.fifth},
    {title: "S-Town", type: Type.fifth},
    {title: "Richard Herring's Leicester Square Theatre Podcast", type: Type.fifth},
    {title: "Homo Sapiens", type: Type.fifth},
    {title: "Too Late to Die Young", type: Type.fifth},
    {title: "The Daily", type: Type.fifth},
    {title: "538 Politics", type: Type.fifth},
    {title: "Song Exploder", type: Type.fifth},
    {title: "The West Wing Weekly", type: Type.fifth},
    {title: "Accidental Tech Podcast", type: Type.fifth},
    {title: "Upgrade", type: Type.fifth},
    {title: "The Cultcast", type: Type.fifth},
    {title: "9to5Mac Happy Hour", type: Type.fifth},
    {title: "Connected", type: Type.fifth},
    {title: "Supercomputer", type: Type.fifth},
    {title: "Automaters", type: Type.fifth},
    {title: "Analog(ue)", type: Type.fifth},
    {title: "AppStories", type: Type.fifth},
    {title: "Command Line Heroes", type: Type.fifth},
    {title: "The Cracked Podcast", type: Type.fifth},
    {title: "Death, Sex and Money", type: Type.fifth},
    {title: "Do By Friday", type: Type.fifth},
    {title: "Fake The Nation", type: Type.fifth},
    {title: "Friends in Your Ears", type: Type.fifth},
    {title: "The Greatest Generation", type: Type.fifth},
    {title: "Heavyweight", type: Type.fifth},
    {title: "JS Party", type: Type.fifth},
    {title: "Left Behind", type: Type.fifth},
    {title: "Persuing Mastery", type: Type.fifth},
    {title: "Radiolab", type: Type.fifth},
    {title: "Random Trek", type: Type.fifth},
    {title: "Reconcilable Differences", type: Type.fifth},
    {title: "Remainiacs - The Brexit Podcast", type: Type.fifth},
    {title: "Reply All", type: Type.fifth},
    {title: "Science Vs", type: Type.fifth},
    {title: "Second Career Devs", type: Type.fifth},
    {title: "Syntax - Tasty Web Development Treats", type: Type.fifth},
    {title: "The Talk Show with John Gruber", type: Type.fifth},
    {title: "This American Life", type: Type.fifth},
    {title: "This Week in Trek: A Star Trek Podcast", type: Type.fifth},
    {title: "Top Four", type: Type.fifth},
    {title: "Under the Radar", type: Type.fifth},
    {title: "Ungeniused", type: Type.fifth},
    {title: "The Dream", type: Type.fifth},
    {title: "The Forecast with Harry Enten", type: Type.fifth},
    {title: "The Greatest Discovery: Star Trek Discovery Reviewed", type: Type.fifth},
    {title: "Stacktrace", type: Type.fifth},
    {title: "Trump, Inc.", type: Type.fifth},
    {title: "Vulcan Hello - A Star Trek Discovery Podcast", type: Type.fifth}
]

games = [
    {title: "Red Dead Redemption 2", type: Type.fourth},
    {title: "God of War", type: Type.fourth},
    {title: "Celeste", type: Type.fourth},
    {title: "Undertale", type: Type.fourth},
    {title: "Super Smash Bros. Ultimate", type: Type.fourth},
    {title: "Forza Horizon 4", type: Type.fourth},
    {title: "Divinity: Original Sin II", type: Type.fourth},
    {title: "Bayonetta 2", type: Type.fourth},
    {title: "INSIDE", type: Type.fourth},
    {title: "Sonic Mania Plus", type: Type.fourth},
    {title: "NieR: Automanta", type: Type.fourth},
    {title: "Bastion", type: Type.fourth},
    {title: "Monster Hunter: World", type: Type.fourth},
    {title: "Astro Bot: Rescue Mission", type: Type.fourth},
    {title: "Into the Breach", type: Type.fourth},
    {title: "Dead Cells", type: Type.fourth},
    {title: "Okami HD", type: Type.fourth},
    {title: "Return of Obra Dinn", type: Type.fourth},
    {title: "DUSK", type: Type.fourth},
    {title: "Hyper Light Drifter", type: Type.fourth},
    {title: "The Banner Saga", type: Type.fourth},
    {title: "Injustice 2", type: Type.fourth},
    {title: "Pillars of Eternity II: Deadfire", type: Type.fourth},
    {title: "Owl Boy", type: Type.fourth},
    {title: "Ikaruga", type: Type.fourth},
    {title: "Diablo III", type: Type.fourth},
    {title: "Subnautica", type: Type.fourth},
    {title: "Street Fighter V: Arcade Edition", type: Type.fourth},
    {title: "Dragon Ball FighterZ", type: Type.fourth},
    {title: "Assassin's Creed Odyssey", type: Type.fourth},
    {title: "Marvel's Spider-Man", type: Type.fourth},
    {title: "Monsterboy and the Cursed Kingdom", type: Type.fourth},
    {title: "Unavowed", type: Type.fourth},
    {title: "Velocity 2X", type: Type.fourth},
    {title: "Iconoclasts", type: Type.fourth},
    {title: "RimWorld", type: Type.fourth},
    {title: "Crypt of the NecroDancer", type: Type.fourth},
    {title: "The Message", type: Type.fourth},
    {title: "Donkey Kong Country: Tropical Freeze", type: Type.fourth},
    {title: "Shantae and the Pirate's Curse", type: Type.fourth},
    {title: "Yakuza 0", type: Type.fourth},
    {title: "Sid Meier's Civilization VI", type: Type.fourth},
    {title: "Transistor", type: Type.fourth},
    {title: "Destiny 2: Forsaken", type: Type.fourth},
    {title: "Dragon Quest XI: Echoes of an Elusive Age", type: Type.fourth},
    {title: "Football Manager 2019", type: Type.fourth},
    {title: "Mini Metro", type: Type.fourth},
    {title: "Dark Souls Remastered", type: Type.fourth},
    {title: "CrossCode", type: Type.fourth},
    {title: "Call of Duty: Black Ops 4", type: Type.fourth},
    {title: "Night in the Woods", type: Type.fourth},
    {title: "DJMax Respect", type: Type.fourth},
    {title: "Full Metal Furies", type: Type.fourth},
    {title: "West of Loathing", type: Type.fourth},
    {title: "Thronebreaker: The Witcher Tales", type: Type.fourth},
    {title: "Darkest Dungeon", type: Type.fourth},
    {title: "Player Unknown's Battlegrounds", type: Type.fourth},
    {title: "Moss", type: Type.fourth},
    {title: "Radiant Historia: Perfect Chronology", type: Type.fourth},
    {title: "428: Shibuya Scramble", type: Type.fourth},
    {title: "Keep Talking and Nobody Explodes", type: Type.fourth},
    {title: "F1 2018", type: Type.fourth},
    {title: "Beat Sabre", type: Type.fourth},
    {title: "Valkyria Chronicles 4", type: Type.fourth},
    {title: "Mega Man X Legacy Collection", type: Type.fourth},
    {title: "Child of Light", type: Type.fourth},
    {title: "Total War: WARHAMMER II - Rise of the Tomb Kings", type: Type.fourth},
    {title: "Kingdom: Two Crowns", type: Type.fourth},
    {title: "Frostpunk", type: Type.fourth},
    {title: "Moonlighter", type: Type.fourth},
    {title: "Hitman 2", type: Type.fourth},
    {title: "GRIS", type: Type.fourth},
    {title: "Just Shapes & Beats", type: Type.fourth},
    {title: "Yoku's Island Express", type: Type.fourth},
    {title: "Assassin's Creed Origins: The Curse of the Pharaohs", type: Type.fourth},
    {title: "Two Point Hospital", type: Type.fourth},
    {title: "Lumines Remastered", type: Type.fourth},
    {title: "Fortnite", type: Type.fourth},
    {title: "Forgotten Anne", type: Type.fourth},
    {title: "The Elder Scrolls Online: Summerset", type: Type.fourth},
    {title: "WindJammers", type: Type.fourth},
    {title: "NBA 2K19", type: Type.fourth},
    {title: "Battle Chef Brigade", type: Type.fourth},
    {title: "Octopath Traveler", type: Type.fourth},
    {title: "Transpose", type: Type.fourth},
    {title: "LIMBO", type: Type.fourth},
    {title: "FIFA 19", type: Type.fourth},
    {title: "Overcooked! 2", type: Type.fourth},
    {title: "Spyro Reignited Trilogy", type: Type.fourth},
    {title: "Flipping Death", type: Type.fourth},
    {title: "Warhammmer: Vermintide 2", type: Type.fourth},
    {title: "Laser League", type: Type.fourth},
    {title: "Shadow of the Tomb Raider", type: Type.fourth},
    {title: "Flat Heroes", type: Type.fourth},
    {title: "NHL 2019", type: Type.fourth},
    {title: "Prey: Mooncrash", type: Type.fourth},
    {title: "Salt and Sanctuary", type: Type.fourth},
    {title: "Far Cry 5", type: Type.fourth},
    {title: "Pro Evolution Soccer 2019", type: Type.fourth},
    {title: "Horizon Chase Turbo", type: Type.fourth},
    {title: "Horizon Zero Dawn", type: Type.fourth}
]

Medium.create(movies)
Medium.create(tv_shows)
Medium.create(podcasts)
Medium.create(games)

def random_medium_generator(x)
  medium_ids = []
  Medium.all.each {|m| medium_ids << m.id }
  return medium_ids.sample(x)
end

queued_media = []
User.all.each do |user|
  random_medium_generator(20).each do |medium_id|
    queued_media << {user_id: user.id, medium_id: medium_id}
  end
end

QueuedMedium.create(queued_media)
